Required liabraries

In [49]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import string
import nltk
import warnings
warnings.filterwarnings('ignore')

In [50]:
#Loading the data set
df=pd.read_csv("Ratings_prediction.csv")

In [51]:
#checking first five rows of data set
df.head()

Unnamed: 0  ratings                                       full_reviews
0           0      1.0  Pathetic quality product, not even worth 1000 ...
1           1      1.0  Apart from showing accurate time & much health...
2           2      1.0  this product does not support with one plus ph...
3           3      1.0  Don't buy this product!!\nI received this prod...
4           4      1.0  Bluetooth coverage is 1 to 2 Mtrs max. Technic...

In [52]:
#we can see that from the data frame we got ratings, full_reviews and unnamed columns. 
#Column unamed is just index with unique values. So we will drop it. 

In [53]:
df.drop(["Unnamed: 0"],axis=1,inplace=True)

In [54]:
df.head()

ratings                                       full_reviews
0      1.0  Pathetic quality product, not even worth 1000 ...
1      1.0  Apart from showing accurate time & much health...
2      1.0  this product does not support with one plus ph...
3      1.0  Don't buy this product!!\nI received this prod...
4      1.0  Bluetooth coverage is 1 to 2 Mtrs max. Technic...

In [55]:
df.shape #checking data dimension

(30424, 2)

In [56]:
df.isnull().sum() #checking for null values

ratings         0
full_reviews    0
dtype: int64

In [57]:
df["ratings"].value_counts() #checking how many ratings are in the data and the total of each rating. 

5.0    6369
1.0    6369
3.0    6349
4.0    6306
2.0    5031
Name: ratings, dtype: int64

In [58]:
# checking the value count with ratio to check how much percentage of each rating in the given data set.
print ('First_rating = ', round(len(df[df['ratings']==1.0]) / len(df.ratings),2)*100,'%')
print ('second_rating  = ', round(len(df[df['ratings']==2.0]) / len(df.ratings),2)*100,'%')
print ('Third_rating = ', round(len(df[df['ratings']==3.0]) / len(df.ratings),2)*100,'%')
print ('Fourth_rating  = ', round(len(df[df['ratings']==4.0]) / len(df.ratings),2)*100,'%')
print ('Fifth_rating = ', round(len(df[df['ratings']==5.0]) / len(df.ratings),2)*100,'%')

First_rating =  21.0 %
second_rating  =  17.0 %
Third_rating =  21.0 %
Fourth_rating  =  21.0 %
Fifth_rating =  21.0 %


In [59]:
#we can see that each rating occupies 21% only the 2 star rating have 17%.  

In [60]:
#Creating new column for the length of full_review.
df["length"]=df.full_reviews.str.len()
df.head()

ratings                                       full_reviews  length
0      1.0  Pathetic quality product, not even worth 1000 ...     243
1      1.0  Apart from showing accurate time & much health...     636
2      1.0  this product does not support with one plus ph...     101
3      1.0  Don't buy this product!!\nI received this prod...     453
4      1.0  Bluetooth coverage is 1 to 2 Mtrs max. Technic...     491

Data Preprocessing.

In [61]:
# Convert all reviews to lower case
df['full_reviews'] = df['full_reviews'].str.lower()

In [62]:
df.head()

ratings                                       full_reviews  length
0      1.0  pathetic quality product, not even worth 1000 ...     243
1      1.0  apart from showing accurate time & much health...     636
2      1.0  this product does not support with one plus ph...     101
3      1.0  don't buy this product!!\ni received this prod...     453
4      1.0  bluetooth coverage is 1 to 2 mtrs max. technic...     491

In [63]:
# Replace numbers with 'numbr'
df['full_reviews'] = df['full_reviews'].str.replace(r'\d+(\.\d+)?', 'numbr')

In [64]:

# Remove punctuation
df['full_reviews'] = df['full_reviews'].str.replace(r'[^\w\d\s]', ' ')

# Replace whitespace between terms with a single space
df['full_reviews'] = df['full_reviews'].str.replace(r'\s+', ' ')

# Remove leading and trailing whitespace
df['full_reviews'] = df['full_reviews'].str.replace(r'^\s+|\s+?$', '')

In [65]:
df.head()

ratings                                       full_reviews  length
0      1.0  pathetic quality product not even worth numbr ...     243
1      1.0  apart from showing accurate time much healthy ...     636
2      1.0  this product does not support with one plus ph...     101
3      1.0  don t buy this product i received this product...     453
4      1.0  bluetooth coverage is numbr to numbr mtrs max ...     491

In [67]:
# Remove stopwords
import string
import nltk
from nltk.corpus import  stopwords

stop_words = set(stopwords.words('english'))

df['full_reviews'] = df['full_reviews'].apply(lambda x: ' '.join(term for term in x.split() if term not in stop_words))

In [68]:
# New column (clean_length) after puncuations,stopwords removal
df['clean_length'] = df['full_reviews'].str.len()
df.head()

ratings                                       full_reviews  length  \
0      1.0  pathetic quality product even worth numbr rupe...     243   
1      1.0  apart showing accurate time much healthy batte...     636   
2      1.0  product support one plus phones worthless prod...     101   
3      1.0  buy product received product numbrrd december ...     453   
4      1.0  bluetooth coverage numbr numbr mtrs max techni...     491   

   clean_length  
0           146  
1           397  
2            65  
3           276  
4           359

In [69]:
print ('Origian Length', df.length.sum())
print ('Clean Length', df.clean_length.sum())

Origian Length 2754264
Clean Length 1932821


In [70]:
#We can see that nearly 825251 un wanted data removed from the original data. 

In [71]:
#we know that Machine understand only numerical data not the text. So here we are going to use NLP.
#NLP(Natural Language processing)
#In NLP there is Bag of words technique, with this we can change the text data into vectors. 
#There are some statistcal techniques to change the text data to vecotrs. 
#Here we are going to take TF-IDF("Term Frequency — Inverse Document Frequency”) technique.

In [73]:
# 1. Convert text into vectors using TF-IDF
# 3. Split reviews and ratings
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

tf_vec = TfidfVectorizer()

naive = MultinomialNB()

features = tf_vec.fit_transform(df['full_reviews'])

x = features
y = df['ratings']

In [76]:
# train_test_split.

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=42)


In [77]:
#Importing machine learning libraries

In [80]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')

In [81]:
#creating Instantiate for Machine Learning Algorithms

In [82]:
Mb=MultinomialNB()
svc=SVC()
knn=KNeighborsClassifier()
lr=LogisticRegression()

In [83]:
#Logistic Regression

In [84]:
lr.fit(x_train,y_train)
pred=lr.predict(x_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

0.537248028045574
[[1387  183  162  102   49]
 [ 437  425  479  144   41]
 [ 294  294  857  309  158]
 [ 146   57  181  971  565]
 [ 129   15   63  416 1264]]
              precision    recall  f1-score   support

         1.0       0.58      0.74      0.65      1883
         2.0       0.44      0.28      0.34      1526
         3.0       0.49      0.45      0.47      1912
         4.0       0.50      0.51      0.50      1920
         5.0       0.61      0.67      0.64      1887

    accuracy                           0.54      9128
   macro avg       0.52      0.53      0.52      9128
weighted avg       0.53      0.54      0.53      9128



In [85]:
#KNN

In [86]:
knn.fit(x_train,y_train)
pred=knn.predict(x_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

0.362182296231376
[[828 364 133 489  69]
 [404 432 196 446  48]
 [365 451 343 616 137]
 [239 241 160 848 432]
 [142 150 107 633 855]]
              precision    recall  f1-score   support

         1.0       0.42      0.44      0.43      1883
         2.0       0.26      0.28      0.27      1526
         3.0       0.37      0.18      0.24      1912
         4.0       0.28      0.44      0.34      1920
         5.0       0.55      0.45      0.50      1887

    accuracy                           0.36      9128
   macro avg       0.38      0.36      0.36      9128
weighted avg       0.38      0.36      0.36      9128



In [87]:
#SVC

In [88]:
svc.fit(x_train,y_train)
pred=svc.predict(x_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

0.55488606485539
[[1419  151  169  100   44]
 [ 394  491  480  119   42]
 [ 304  236  897  308  167]
 [ 144   42  183  923  628]
 [ 135    9   58  350 1335]]
              precision    recall  f1-score   support

         1.0       0.59      0.75      0.66      1883
         2.0       0.53      0.32      0.40      1526
         3.0       0.50      0.47      0.48      1912
         4.0       0.51      0.48      0.50      1920
         5.0       0.60      0.71      0.65      1887

    accuracy                           0.55      9128
   macro avg       0.55      0.55      0.54      9128
weighted avg       0.55      0.55      0.54      9128



In [89]:
#Naive Bayes

In [90]:
Mb.fit(x_train,y_train)
pred=Mb.predict(x_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

0.5287028921998247
[[1388  101  220   68  106]
 [ 450  203  649  130   94]
 [ 305  114 1007  213  273]
 [ 158   29  216  692  825]
 [ 114    2   64  171 1536]]
              precision    recall  f1-score   support

         1.0       0.57      0.74      0.65      1883
         2.0       0.45      0.13      0.21      1526
         3.0       0.47      0.53      0.50      1912
         4.0       0.54      0.36      0.43      1920
         5.0       0.54      0.81      0.65      1887

    accuracy                           0.53      9128
   macro avg       0.52      0.51      0.49      9128
weighted avg       0.52      0.53      0.50      9128



In [94]:
#from the above 4 algorithms result we can see that "SVC" is working better when compared with other algorithms. 
#SVC Better f1 score compared to other algorithms

In [98]:
#We will save SVC model to predict ratings for the customers who provided reviews in past.

In [99]:
import pickle#importing pickle to save the model.
filename= 'picklelgfile.pkl'
pickle.dump(svc, open(filename,'wb')) #------------------>>>>saving model
loaded_model=pickle.load(open(filename,'rb'))#------------------>>>>example for reloading the model for predicting new data
loaded_model.predict(x_test).

array([3., 3., 1., ..., 1., 4., 2.])